### ISSUE TITLE
Markdown generated html gets escaped

### ISSUE THREAD

**Issue by ohcibi** [theasta/jsdoc-dash-template#1]
I just generated a docset with the `markdown` plugin enabled. The problem is now that because this templates html-escapes all the descriptions as in this https://github.com/theasta/jsdoc-dash-template/commit/6983e3e560cdd0f1b7db583873761cd3f46e2409 commit, the generated markdown also gets escaped.

As markdown escapes raw html anyways, the escaping wouldn't be necessary if the plugin was used, but I have to little knowledge about jsdoc templates to fix this myself.

**Comment by Obbut** [comment]
I have this issue as well.

**Comment by theasta** [comment]
I really think escaping should be the default but it is really difficult to extend jsdoc. I reverted my change. It is possible to force escaping by adding the [escapeHtml plugin](https://github.com/jsdoc3/jsdoc/blob/3dbb94f157290e8a0cbc79cb3580130e8e2c4534/plugins/escapeHtml.js)

**Comment by theasta** [comment]
@Obbut Can you take a shot at v2.0.1?

**Comment by ohcibi** [comment]
In JavaDoc Html Is used to Format the docs and this is actually quite useful, so I'd say escaping being not the default is the right way. There is no need to extend anything if we can simply opt in to either markdown or html or escaped html as we like. Just keep it that way

**Comment by theasta** [comment]
@ohcibi this plugin is only for JSDoc not JavaDoc.

> There is no need to extend anything if we can simply opt in to either markdown or html or escaped html as we like.

This is why I meant too. Not that simple though. Feel free to send me a PR, I'd be happy to merge it.

**Comment by ohcibi** [comment]
@Theasta. I Know that this is not for java doc, I was just giving an example why escaping should not be the default and my point was that this is good now. By opt-in I meant the escapehtml plugin. I'd just leave it as is and tell people to use escapehtml if they really want to escape html.

**Comment by Obbut** [comment]
2.0.1 works fine, thanks!
